CREATE TABLE Studenti (matricola INTEGER PRIMARY KEY NOT NULL, nome TEXT NOT NULL, cognome TEXT NOT NULL, telefono TEXT);
.tables
.schema Studenti
.schema Studenti
INSERT INTO Studenti (matricola, nome, cognome, telefono) VALUES (1001, "Mario", "Rossi", "33810011001");
SELECT * FROM Studenti;
INSERT INTO Studenti (matricola, nome, cognome, telefono) VALUES (1002, "Giuseppe", "Verdi", "33810021002"), (1003, "Marco", "Bianchi", "33810031003");
SELECT * FROM Studenti;
SELECT * FROM Studenti;
-- DROP TABLE Studenti;
.tables
UPDATE Studenti SET telefono = "33810041004" WHERE matricola = 1003;
SELECT * FROM Studenti;
INSERT INTO Studenti (matricola, nome, cognome, telefono) VALUES (1001, "Mario", "Rossi", "33810011001");
SELECT * FROM Studenti WHERE matricola > 1002;
SELECT cognome, telefono FROM Studenti WHERE matricola <= 1002;
CREATE TABLE Docenti (id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT NOT NULL, cognome TEXT NOT NULL);
INSERT INTO Docenti (nome, cognome) VALUES ("Pierpaolo", "Loreti");
SELECT * FROM Docenti;
INSERT INTO Docenti (nome, cognome) VALUES ("Andrea", "Detti");
SELECT * FROM Docenti;
CREATE TABLE Corsi (codice TEXT PRIMARY KEY NOT NULL, docente INTEGER NOT NULL,    FOREIGN KEY (docente) REFERENCES Docenti(id));
INSERT INTO Corsi (codice, docente) VALUES ("PDM", 1);
SELECT * FROM Corsi;
SELECT * FROM Docenti WHERE id = 1;
INSERT INTO Corsi (codice, docente) VALUES ("SRD", 3);
SELECT * FROM Corsi;
DELETE FROM Corsi WHERE codice = "SRD";
SELECT * FROM Corsi;
SELECT * FROM Docenti;
SELECT Corsi.codice, Docenti.nome, Docenti.cognome FROM Corsi JOIN Docenti ON Corsi.docente = Docenti.id;
CREATE TABLE Esami (studente INTEGER, corso TEXT, voto INTEGER CHECK (voto >= 18 AND voto <= 30), data DATETIME DEFAULT CURRENT_DATE, FOREIGN KEY (studente) REFERENCES Studenti(matricola), FOREIGN KEY (corso) REFERENCES Corsi(codice), PRIMARY KEY (studente, corso));
INSERT INTO Esami (studente, corso, voto) VALUES (1001, "PDM", 27);
SELECT * FROM Esami;
INSERT INTO Esami (studente, corso, voto) VALUES (1002, "PDM", 17);
INSERT INTO Esami (studente, corso, voto) VALUES (1002, "PDM", 18);
INSERT INTO Esami (studente, corso, voto, data) VALUES (1003, "PDM", 28, "2012-12-01");
SELECT * FROM Esami;
SELECT * FROM Corsi;
INSERT INTO Corsi (codice, docente) VALUES ("TPI2", 2);
SELECT * FROM Corsi;
INSERT INTO Esami (studente, corso, voto, data) VALUES (1001, "TPI2", 29, "2012-11-11");
INSERT INTO Esami (studente, corso, voto, data) VALUES (1003, "TPI2", 28, "2012-11-11");
SELECT * FROM Esami;
SELECT studente, corso, voto, data FROM Esami WHERE matricola = 1001;
SELECT studente, corso, voto, data FROM Esami WHERE studente = 1001;
SELECT Studenti.nome, Studenti.cognome, Esami.corso, Esami.voto, Esami.data FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente WHERE Esami.studente = 1001;
SELECT Studenti.nome, Studenti.cognome, Esami.corso, Esami.voto, Esami.data FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente;
SELECT Studenti.nome, Studenti.cognome, Esami.corso, Esami.voto, Esami.data FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente ORDER BY Studenti.cognome;
SELECT Studenti.nome, Studenti.cognome, Esami.corso, Esami.voto, Esami.data FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente ORDER BY Studenti.cognome ASC;
SELECT Studenti.nome, Studenti.cognome, Esami.corso, Esami.voto, Esami.data FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente ORDER BY Studenti.cognome DESC;
SELECT Studenti.nome, Studenti.cognome, Esami.corso, Esami.voto, Esami.data FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente ORDER BY Studenti.cognome DESC;
SELECT * FROM Studenti JOIN Esami;
SELECT * FROM Studenti JOIN Esami;
SELECT Studenti.nome, Studenti.cognome, Esami.corso, Esami.voto, Esami.data FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente ORDER BY Studenti.cognome DESC;
SELECT Studenti.nome, Studenti.cognome, Esami.corso, Esami.voto, Esami.data FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente ORDER BY Studenti.cognome DESC;
SELECT Studenti.nome, Studenti.cognome, Esami.corso, Esami.voto, Docenti.nome, Docenti.cognome FROM ((Studenti JOIN Esami ON Studenti.matricola = Esami.studente) JOIN Corsi ON Esami.corso = Corsi.codice) JOIN Docenti ON Corsi.docente = Docenti.id;
SELECT Studenti.nome, Studenti.cognome, AVG(Esami.voto) FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente GROUP BY Studenti.matricola;
SELECT Studenti.nome, Studenti.cognome, AVG(Esami.voto) FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente;
SELECT Studenti.nome, Studenti.cognome, AVG(Esami.voto) FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente GROUP BY Studenti.matricola;
SELECT Studenti.nome, Studenti.cognome, AVG(Esami.voto), COUNT(Esami.voto) FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente GROUP BY Studenti.matricola;
SELECT Studenti.nome, Studenti.cognome, AVG(Esami.voto), COUNT(Esami.voto) FROM Studenti JOIN Esami ON Studenti.matricola = Esami.studente GROUP BY Studenti.matricola HAVING Studenti.matricola = 1001;
